// <auto-generated />
using System;
using BattleShips.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BattleShips.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200508100134_InitialWithSeed")]
    partial class InitialWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BattleShips.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPlayedGames")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1abc922-d551-4fd5-8f98-aa2a915cbec3",
                            Email = "player1@pslib.cz",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PLAYER1@PSLIB.CZ",
                            NormalizedUserName = "PLAYER1@PSLIB.CZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEP6fMWCJXnEht0lxMRHtkrtDphMQdQHesFZ7F7CQz/AKx8HHipQO7Ojxmj+Fphf3qw==",
                            PhoneNumberConfirmed = false,
                            PlayerName = "Player1",
                            SecurityStamp = "39c6972a-a1bf-4f23-a77e-bf96f7cfc5b6",
                            TotalPlayedGames = 10,
                            TwoFactorEnabled = false,
                            UserName = "player1@pslib.cz",
                            Wins = 3
                        },
                        new
                        {
                            Id = "121525be-385a-48c7-b5a7-2194757075fd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61fc5550-097b-47a8-b7d2-bb43a5910515",
                            Email = "player2@pslib.cz",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PLAYER2@PSLIB.CZ",
                            NormalizedUserName = "PLAYER2@PSLIB.CZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEP6fMWCJXnEht0lxMRHtkrtDphMQdQHesFZ7F7CQz/AKx8HHipQO7Ojxmj+Fphf3qw==",
                            PhoneNumberConfirmed = false,
                            PlayerName = "Player2",
                            SecurityStamp = "6aa3382d-f2c2-46be-aa29-43d7e5b8cead",
                            TotalPlayedGames = 10,
                            TwoFactorEnabled = false,
                            UserName = "player2@pslib.cz",
                            Wins = 6
                        },
                        new
                        {
                            Id = "7c4e532f-1d0d-4d6b-b521-e81eadd79543",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e44bbc0f-e746-4417-ac1e-4ef03a251428",
                            Email = "player3@pslib.cz",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PLAYER3@PSLIB.CZ",
                            NormalizedUserName = "PLAYER3@PSLIB.CZ",
                            PasswordHash = "AQAAAAEAACcQAAAAEP6fMWCJXnEht0lxMRHtkrtDphMQdQHesFZ7F7CQz/AKx8HHipQO7Ojxmj+Fphf3qw==",
                            PhoneNumberConfirmed = false,
                            PlayerName = "Player3",
                            SecurityStamp = "df550323-fdc2-4c6d-ae86-9a2782ebe8d2",
                            TotalPlayedGames = 12,
                            TwoFactorEnabled = false,
                            UserName = "player3@pslib.cz",
                            Wins = 3
                        });
                });

            modelBuilder.Entity("BattleShips.Data.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentPlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GameRound")
                        .HasColumnType("int");

                    b.Property<int>("GameSize")
                        .HasColumnType("int");

                    b.Property<int>("GameState")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserRound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlayerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80828d2b-e7e0-4316-aa6b-cea1d08f413c"),
                            CurrentPlayerId = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            GameRound = 0,
                            GameSize = 2,
                            GameState = 0,
                            MaxPlayers = 2,
                            OwnerId = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            UserRound = 0
                        },
                        new
                        {
                            Id = new Guid("80828d2b-e7e0-4316-aa6b-cea1d08f413e"),
                            CurrentPlayerId = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            GameRound = 0,
                            GameSize = 2,
                            GameState = 2,
                            MaxPlayers = 2,
                            OwnerId = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            UserRound = 0
                        });
                });

            modelBuilder.Entity("BattleShips.Data.NavyBattlePiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int>("PieceState")
                        .HasColumnType("int");

                    b.Property<int>("PosX")
                        .HasColumnType("int");

                    b.Property<int>("PosY")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserGameId");

                    b.ToTable("NavyBattlePieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hidden = true,
                            PieceState = 1,
                            PosX = 0,
                            PosY = 0,
                            TypeId = 1,
                            UserGameId = 1
                        },
                        new
                        {
                            Id = 2,
                            Hidden = true,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 0,
                            TypeId = 1,
                            UserGameId = 1
                        },
                        new
                        {
                            Id = 3,
                            Hidden = true,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 1,
                            TypeId = 1,
                            UserGameId = 1
                        },
                        new
                        {
                            Id = 4,
                            Hidden = true,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 1,
                            TypeId = 1,
                            UserGameId = 1
                        },
                        new
                        {
                            Id = 5,
                            Hidden = true,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            TypeId = 1,
                            UserGameId = 2
                        },
                        new
                        {
                            Id = 6,
                            Hidden = true,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 0,
                            TypeId = 1,
                            UserGameId = 2
                        },
                        new
                        {
                            Id = 7,
                            Hidden = true,
                            PieceState = 1,
                            PosX = 0,
                            PosY = 1,
                            TypeId = 1,
                            UserGameId = 2
                        },
                        new
                        {
                            Id = 8,
                            Hidden = true,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            TypeId = 1,
                            UserGameId = 2
                        });
                });

            modelBuilder.Entity("BattleShips.Data.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Submarine"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Destroyer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cruiser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Battleship"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aircraft carrier"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Landing base"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hydro plane"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cruiser II"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Heavy Cruiser"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Catamaran"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Light battleship"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Aircraft carrier II"
                        });
                });

            modelBuilder.Entity("BattleShips.Data.ShipGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipGames");
                });

            modelBuilder.Entity("BattleShips.Data.ShipPiece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PieceState")
                        .HasColumnType("int");

                    b.Property<int>("PosX")
                        .HasColumnType("int");

                    b.Property<int>("PosY")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipPieces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 2,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 3,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 4,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 5,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 6,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 7,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 8,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 9,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 1
                        },
                        new
                        {
                            Id = 10,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 11,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 12,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 13,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 14,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 15,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 16,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 17,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 18,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 19,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 20,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 21,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 2
                        },
                        new
                        {
                            Id = 22,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 23,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 24,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 25,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 26,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 27,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 28,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 29,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 30,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 31,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 32,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 33,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 34,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 35,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 36,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 3
                        },
                        new
                        {
                            Id = 37,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 350,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 360,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 370,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 38,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 39,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 40,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 41,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 42,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 43,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 44,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 45,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 46,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 47,
                            PieceState = 1,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 48,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 49,
                            PieceState = 0,
                            PosX = 5,
                            PosY = 0,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 50,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 1,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 51,
                            PieceState = 0,
                            PosX = 5,
                            PosY = 2,
                            ShipId = 4
                        },
                        new
                        {
                            Id = 52,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 53,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 54,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 55,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 56,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 57,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 58,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 59,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 60,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 61,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 62,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 63,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 64,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 65,
                            PieceState = 1,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 66,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 67,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 68,
                            PieceState = 1,
                            PosX = 5,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 69,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 70,
                            PieceState = 0,
                            PosX = 6,
                            PosY = 0,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 71,
                            PieceState = 4,
                            PosX = 6,
                            PosY = 1,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 72,
                            PieceState = 0,
                            PosX = 6,
                            PosY = 2,
                            ShipId = 5
                        },
                        new
                        {
                            Id = 73,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 74,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 75,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 76,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 77,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 78,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 79,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 80,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 81,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 82,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 83,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 84,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 85,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 86,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 87,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 88,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 89,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 90,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 91,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 92,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 3,
                            ShipId = 6
                        },
                        new
                        {
                            Id = 93,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 94,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 95,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 96,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 97,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 98,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 99,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 100,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 101,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 102,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 103,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 104,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 105,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 106,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 107,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 108,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 109,
                            PieceState = 0,
                            PosX = 5,
                            PosY = 0,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 110,
                            PieceState = 0,
                            PosX = 5,
                            PosY = 1,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 111,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 2,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 112,
                            PieceState = 0,
                            PosX = 5,
                            PosY = 3,
                            ShipId = 7
                        },
                        new
                        {
                            Id = 113,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 114,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 115,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 116,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 117,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 118,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 119,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 120,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 121,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 122,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 123,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 124,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 125,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 126,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 127,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 128,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 129,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 130,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 131,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 132,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 3,
                            ShipId = 8
                        },
                        new
                        {
                            Id = 133,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 134,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 135,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 136,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 137,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 4,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 138,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 139,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 140,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 141,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 142,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 4,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 143,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 144,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 145,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 146,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 147,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 4,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 148,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 149,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 150,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 151,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 152,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 4,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 153,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 154,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 155,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 156,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 3,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 157,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 4,
                            ShipId = 9
                        },
                        new
                        {
                            Id = 158,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 159,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 160,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 161,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 162,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 4,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 163,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 164,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 165,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1660,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1670,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 4,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1680,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1690,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1700,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1710,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1720,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 4,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1730,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1740,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 1750,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 166,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 167,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 4,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 168,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 169,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 170,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 171,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 3,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 172,
                            PieceState = 0,
                            PosX = 4,
                            PosY = 4,
                            ShipId = 10
                        },
                        new
                        {
                            Id = 173,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 174,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 175,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 176,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 177,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 178,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 179,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 180,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 181,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 182,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 183,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 184,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 185,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 186,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 187,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 1880,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 11
                        },
                        new
                        {
                            Id = 188,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 189,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 190,
                            PieceState = 4,
                            PosX = 0,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 191,
                            PieceState = 0,
                            PosX = 0,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 192,
                            PieceState = 0,
                            PosX = 1,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 193,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 194,
                            PieceState = 1,
                            PosX = 1,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 195,
                            PieceState = 4,
                            PosX = 1,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 196,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 197,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 198,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 199,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 200,
                            PieceState = 0,
                            PosX = 2,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 201,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 202,
                            PieceState = 1,
                            PosX = 2,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 203,
                            PieceState = 4,
                            PosX = 2,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 204,
                            PieceState = 0,
                            PosX = 3,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 205,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 206,
                            PieceState = 1,
                            PosX = 3,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 207,
                            PieceState = 4,
                            PosX = 3,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 208,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 209,
                            PieceState = 1,
                            PosX = 4,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 210,
                            PieceState = 1,
                            PosX = 4,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 211,
                            PieceState = 4,
                            PosX = 4,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 212,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 213,
                            PieceState = 1,
                            PosX = 5,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 214,
                            PieceState = 1,
                            PosX = 5,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 215,
                            PieceState = 4,
                            PosX = 5,
                            PosY = 3,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 216,
                            PieceState = 0,
                            PosX = 6,
                            PosY = 0,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 217,
                            PieceState = 4,
                            PosX = 6,
                            PosY = 1,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 218,
                            PieceState = 4,
                            PosX = 6,
                            PosY = 2,
                            ShipId = 12
                        },
                        new
                        {
                            Id = 219,
                            PieceState = 0,
                            PosX = 6,
                            PosY = 3,
                            ShipId = 12
                        });
                });

            modelBuilder.Entity("BattleShips.Data.ShipUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.Property<int>("UserGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.HasIndex("UserGameId");

                    b.ToTable("ShipUsers");
                });

            modelBuilder.Entity("BattleShips.Data.UserGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("GameId");

                    b.ToTable("UserGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "b71cf7ca-c377-49f6-9248-d8d429de0bc5",
                            GameId = new Guid("80828d2b-e7e0-4316-aa6b-cea1d08f413e"),
                            PlayerState = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "121525be-385a-48c7-b5a7-2194757075fd",
                            GameId = new Guid("80828d2b-e7e0-4316-aa6b-cea1d08f413e"),
                            PlayerState = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BattleShips.Data.Game", b =>
                {
                    b.HasOne("BattleShips.Data.ApplicationUser", "CurrentPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentPlayerId");

                    b.HasOne("BattleShips.Data.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleShips.Data.NavyBattlePiece", b =>
                {
                    b.HasOne("BattleShips.Data.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleShips.Data.UserGame", "UserGame")
                        .WithMany()
                        .HasForeignKey("UserGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleShips.Data.ShipGame", b =>
                {
                    b.HasOne("BattleShips.Data.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleShips.Data.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleShips.Data.ShipPiece", b =>
                {
                    b.HasOne("BattleShips.Data.Ship", "Ship")
                        .WithMany("ShipPieces")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleShips.Data.ShipUser", b =>
                {
                    b.HasOne("BattleShips.Data.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleShips.Data.UserGame", "UserGame")
                        .WithMany()
                        .HasForeignKey("UserGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BattleShips.Data.UserGame", b =>
                {
                    b.HasOne("BattleShips.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("BattleShips.Data.Game", "Game")
                        .WithMany("UserGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BattleShips.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BattleShips.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BattleShips.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BattleShips.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
